<?php
/*
  29o3 content management system
  (c) 2003-2004 by Ulrik Guenther <kpanic@00t.org>
  This software subjects to the license described in the
  file LICENSE you should have received with this distribution.

  Blank configuration file, rename to config.php and edit.
*/

$CONFIG = array(
	/*** DATABASE CONFIGURATION ***/
	"DatabaseType" 		=>	"postgresql",		// Type of database, currently possible: postgresql
	"DatabaseHost"		=>	"",			// Host name/IP address of the database server
	"DatabaseUser" 		=>	"",			// username for database access
	"DatabasePassword"	=>	"",			// password for database access
	"DatabasePort"		=>	"",			// port for database connection, leave blank for standard
	"DatabaseName"		=>	"",			// name of the database to use
	"DatabasePrefix"	=>	"broend_",		// prefix of the tables for 29o3
	
	/*** 29o3 DIRECTORY CONFIGURATION ***/
	/* A trailing slash at the end of both of these entries is important */
	"LibDir"		=>	"/var/www//29o3/lib/",	// path to 29o3 libraries, has to be edited!
	"MediaDir"		=>	"/var/www/29o3/media/", // path to 29o3 media (images, etc.), has to be edited!
	
	/*** 29o3 COMMON CONFIGURATION ***/
	"SiteAuthor"		=>	"",			// author/owner of the website
	"SiteAddress"		=>	"",			// address of the site
	"CriticalNotify"	=>	false,			// should the admin be informed about critical errors?
	"CriticalNotifyAddr"	=>	"",			// address of the admin
	"CriticalNotifyCC"	=>	"",			// additional people you want to keep informed about problems
	
	/*** STYLE CONFIGURATION ***/
	"GlobalStylesheetFile"	=>	"n_style.css",		// file of the stylesheet used for all pages generated by 29o3
	
	/*** DEVELOPER CONFIGURATION ***/
	/*** WARNING: DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING!!! ***/
	/***	      29o3 WILL WORK PERFECTLY WITH NO ADJUSTMENT TO      ***/
	/***	      THESE OPTIONS.					  ***/
	"Developer_Debug"	=>	true,
	"Developer_Features"	=>	true,
	"DebugLevel"		=>	5
);

/*********************************************************************************/
/**!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**/
/**! WARNING: ALTERING THE FOLLOWING LINES CAN CAUSE 29o3 NOT TO WORK PROPERLY !**/
/**!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**/
/*********************************************************************************/

$SYSTEM_INFO = array(
	"SystemVersion"		=>	"0.1prebeta",
	"SystemCodename"	=>	"broend",
	"SystemFeatures"	=>	"postgres",
	"MinPhpVersion"		=>	"5.0.0"
);

?>
